# Generated by Django 2.1.5 on 2019-12-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(default='Default Category', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='featuring',
            field=models.CharField(default='Me', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
